import Head from 'next/head'
import Pokedex from './pokedex';
import { GetServerSideProps } from 'next';
import { InferGetServerSidePropsType } from 'next';

type Repo = {
  name: string
  stargazers_count: number
}

export const getServerSideProps: GetServerSideProps<{ repo: Repo }> = async () => {
  const response = await fetch('https://pokeapi.co/api/v2/pokemon/?limit=100')
  const repo = await response.json()
  return { props: { repo } }
}

export default function Home({ repo }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Pokedex.png" />
      </Head>

      <Pokedex
        repo={repo}/>
    </>
  )
}
