import Head from 'next/head'
import Link from 'next/link';
import { useRouter } from 'next/router';
import PokeTrainer from '../../../../components/PokeTrainer/PokeTrainer';
import ViewPokemon from '../../../../components/Views/ViewPokemon/ViewPokemon';


export default function Pokemon() {
    let router = useRouter();
    let id = router?.query?.id;

    if (!id) return <h1> Cargando: Id no proporcionado </h1>
    if (id) {
        return (
            <>
                <Head>
                    <title>Pokedex: {id}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/Pokedex.png" />
                </Head>

                <div>
                    <Link href={'/'}> Atras </Link>
                </div>

                <PokeTrainer />

                <ViewPokemon
                    id={`${id}`} />

            </>
        )
    }
}
